name       : checker-framework          # name of the package
version    : 1.9.4-3       # version of the package
kind       : tool                     # one of tool or spec(s)
description: The Checker Framework enhances the Java type system to make it more powerful and useful.

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com



assets:
    - asset   : MAIN
      name    : checker-framework-dist
      url     : http://types.cs.washington.edu/checker-framework/current/checker-framework.zip
      platform: all
        

# downloads everything to the .
install:
  - cmd: unzip MAIN
    description: Unpacking the Checker Framework Distribution (version 1.9.4)
    platform: all
  - cmd: mv checker-framework*/checker .
    description: Restructuring distribution...
    platform: all

        